### ISSUE TITLE
дамп базы данных голосования

### ISSUE THREAD

**Issue by uhfband** [50000-Quaoar/election2021_msk#1]
observer.mos.ru уже не работает, не расшарит ли добрый человек дамп по одномандатным округам?

**Comment by uhfband** [comment]
Вроде поднялся observer.mos.ru. Я уж думал, он совсем.

**Comment by 50000-Quaoar** [comment]
Да, он плох в последнее время. Ссылки на альтернативные источники дампов добавлю, но всё что скачано не из официальных источников надо обязательно сверять по чексумме.
